// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PQGD.Data;

#nullable disable

namespace PQGD.Migrations
{
    [DbContext(typeof(data_context))]
    [Migration("20231011122811_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PQGD.Models.GiaoVien", b =>
                {
                    b.Property<int>("id_giaovien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_giaovien"));

                    b.Property<bool>("admin")
                        .HasColumnType("bit");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gioitinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("matkhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngaysinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("takhoan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_giaovien");

                    b.ToTable("GiaoViens");
                });

            modelBuilder.Entity("PQGD.Models.HocKy", b =>
                {
                    b.Property<int>("Id_hocky")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_hocky"));

                    b.Property<string>("namhoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenhocky")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_hocky");

                    b.ToTable("HocKys");
                });

            modelBuilder.Entity("PQGD.Models.Lop", b =>
                {
                    b.Property<int>("id_lop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_lop"));

                    b.Property<string>("tenlop")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_lop");

                    b.ToTable("Lops");
                });

            modelBuilder.Entity("PQGD.Models.MonHoc", b =>
                {
                    b.Property<int>("id_monhoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_monhoc"));

                    b.Property<string>("tenmonhoc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_monhoc");

                    b.ToTable("MonHocs");
                });

            modelBuilder.Entity("PQGD.Models.PhanQuyen", b =>
                {
                    b.Property<int>("id_phanquyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_phanquyen"));

                    b.Property<int>("id_giaovien")
                        .HasColumnType("int");

                    b.Property<int>("id_hocky")
                        .HasColumnType("int");

                    b.Property<int>("id_lop")
                        .HasColumnType("int");

                    b.Property<int>("id_monhoc")
                        .HasColumnType("int");

                    b.HasKey("id_phanquyen");

                    b.HasIndex("id_giaovien");

                    b.HasIndex("id_hocky");

                    b.HasIndex("id_lop");

                    b.HasIndex("id_monhoc");

                    b.ToTable("PhanQuyens");
                });

            modelBuilder.Entity("PQGD.Models.PhanQuyen", b =>
                {
                    b.HasOne("PQGD.Models.GiaoVien", "GiaoVien")
                        .WithMany()
                        .HasForeignKey("id_giaovien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PQGD.Models.HocKy", "HocKy")
                        .WithMany()
                        .HasForeignKey("id_hocky")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PQGD.Models.Lop", "Lop")
                        .WithMany()
                        .HasForeignKey("id_lop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PQGD.Models.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("id_monhoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaoVien");

                    b.Navigation("HocKy");

                    b.Navigation("Lop");

                    b.Navigation("MonHoc");
                });
#pragma warning restore 612, 618
        }
    }
}
